(function(){window.WPD="undefined"!==typeof window.WPD?window.WPD:{};if("undefined"!=typeof WPD.dom&&1<WPD.dom.version)return!1;WPD.dom=function(){if("undefined"==typeof WPD.dom.fn||"undefined"==typeof WPD.dom.fn.a)WPD.dom.fn={a:[],is_wpd_dom:!0,length:0,get:function(c){return"undefined"==typeof c?this.a.slice():"undefined"!=typeof this.a[c]?this.a[c]:null},_:function(c){return"<"===c.charAt(0)?WPD.dom._fn.createElementsFromHTML(c):Array.prototype.slice.call(document.querySelectorAll(c))},$:function(c,
a){let b=this.copy(this,!0);b.a="undefined"!=typeof a?null!==a?a.find(c).get():[]:"string"==typeof c?b._(c):null!==c?[c]:[];b.length=b.a.length;return b},extend:function(){for(let c=1;c<arguments.length;c++)for(let a in arguments[c])arguments[c].hasOwnProperty(a)&&(arguments[0][a]=arguments[c][a]);return arguments[0]},copy:function(c,a){let b,d,e;if("object"!=typeof c||null===c)return c;b=new c.constructor;for(d in c)c.hasOwnProperty(d)&&(e=typeof c[d],b[d]=a&&"object"===e&&null!==c[d]?this.copy(c[d]):
c[d]);return b},parent:function(c){let a=this.get(0),b=this.copy(this,!0);b.a=[];null!=a&&(a=a.parentElement,"undefined"!=typeof c?a.matches(c)&&(b.a=[a]):b.a=null==a?[]:[a]);return b},first:function(){let c=this.copy(this,!0);c.a="undefined"!=typeof c.a[0]?[c.a[0]]:[];c.length=c.a.length;return c},last:function(){let c=this.copy(this,!0);c.a=0<c.a.length?[c.a[c.a.length-1]]:[];c.length=c.a.length;return c},prev:function(c){let a=this.copy(this,!0);if("undefined"==typeof c)a.a="undefined"!=typeof a.a[0]&&
null!=a.a[0].previousElementSibling?[a.a[0].previousElementSibling]:[];else if("undefined"!=typeof a.a[0]){let b=a.a[0].previousElementSibling;for(a.a=[];null!=b;){if(b.matches(c)){a.a=[b];break}b=b.previousElementSibling}}a.length=a.a.length;return a},next:function(c){let a=this.copy(this,!0);if("undefined"==typeof c)a.a="undefined"!=typeof a.a[0]&&null!=a.a[0].nextElementSibling?[a.a[0].nextElementSibling]:[];else if("undefined"!=typeof a.a[0]){let b=a.a[0].nextElementSibling;for(a.a=[];null!=b;){if(b.matches(c)){a.a=
[b];break}b=b.nextElementSibling}}a.length=a.a.length;return a},closest:function(c){let a=this.get(0),b=this.copy(this,!0);b.a=[];if("string"===typeof c){if(null!==a&&"undefined"!=typeof a.matches&&""!==c){if(!a.matches(c))for(;(a=a.parentElement)&&!a.matches(c););b.a=null==a?[]:[a]}}else if(null!==a&&"undefined"!=typeof a.matches&&"undefined"!=typeof c.matches){if(a!==c)for(;(a=a.parentElement)&&a!==c;);b.a=null==a?[]:[a]}b.length=b.a.length;return b},add:function(c){if("undefined"!==typeof c)if("undefined"!==
typeof c.nodeType)-1==this.a.indexOf(c)&&this.a.push(c);else if("undefined"!==typeof c.a){let a=this;c.a.forEach(function(b){-1==a.a.indexOf(b)&&a.a.push(b)})}return this},find:function(c){let a=this.copy(this,!0);a.a=[];this.forEach(function(b){null!==b&&"undefined"!=typeof b.querySelectorAll&&(a.a=a.a.concat(Array.prototype.slice.call(b.querySelectorAll(c))))});a.length=a.a.length;return a},forEach:function(c){this.a.forEach(function(a,b,d){c.apply(a,[a,b,d])});return this},each:function(c){return this.forEach(c)},
hasClass:function(c){let a=this.get(0);return null!=a?a.classList.contains(c):!1},addClass:function(c){let a=c;"string"==typeof c&&(a=c.split(" "));a=a.filter(function(b){return""!==b.trim()});0<a.length&&this.forEach(function(b){b.classList.add.apply(b.classList,a)});return this},removeClass:function(c){if("undefined"!=typeof c){let a=c;"string"==typeof c&&(a=c.split(" "));a=a.filter(function(b){return""!==b.trim()});0<a.length&&this.forEach(function(b){b.classList.remove.apply(b.classList,a)})}else this.forEach(function(a){0<
a.classList.length&&a.classList.remove.apply(a.classList,a.classList)});return this},is:function(c){let a=this.get(0);return null!=a?a.matches(c):!1},val:function(c){let a=this.get(0);if(null!=a)if(1==arguments.length)if("select-multiple"==a.type){c="string"===typeof c?c.split(","):c;for(let b=0,d=a.options.length,e;b<d;b++)e=a.options[b],e.selected=-1!=c.indexOf(e.value)}else a.value=c;else return"select-multiple"==a.type?Array.prototype.map.call(a.selectedOptions,function(b){return b.value}):a.value;
return this},isVisible:function(){let c=this.get(0),a=!0,b;for(;null!==c;){b=window.getComputedStyle(c);if("none"==b.display||"hidden"==b.visibility||0==b.opacity){a=!1;break}c=c.parentElement}return a},attr:function(c,a){let b,d=arguments,e=this;this.forEach(function(f){2==d.length?(f.setAttribute(c,a),b=e):"object"===typeof c?Object.keys(c).forEach(function(g){f.setAttribute(g,c[g])}):b=f.getAttribute(c)});return b},removeAttr:function(c){this.forEach(function(a){a.removeAttribute(c)});return this},
prop:function(c,a){let b,d=arguments;this.forEach(function(e){2==d.length?e[c]=a:b="undefined"!=typeof e[c]?e[c]:null});return 2==d.length?this:b},data:function(c,a){let b=this.get(0),d=c.replace(/-([a-z])/g,function(e){return e[1].toUpperCase()});return null!=b?2==arguments.length?(b.dataset[d]=a,this):"undefined"==typeof b.dataset[d]?"":b.dataset[d]:""},html:function(c){let a=this.get(0);return null!=a?1==arguments.length?(a.innerHTML=c,this):a.innerHTML:""},text:function(c){let a=this.get(0);return null!=
a?1==arguments.length?(a.textContent=c,this):a.textContent:""},css:function(c,a){let b=this.get(),d;for(let e=0;e<b.length;e++)if(d=b[e],1==arguments.length)if("object"==typeof c)Object.keys(c).forEach(function(f){d.style[f]=c[f]});else return window.getComputedStyle(d)[c];else d.style[c]=a;return this},position:function(){let c=this.get(0);return null!=c?{top:c.offsetTop,left:c.offsetLeft}:{top:0,left:0}},offset:function(){let c=this.get(0);return null!=c?WPD.dom._fn.hasFixedParent(c)?c.getBoundingClientRect():
WPD.dom._fn.absolutePosition(c):{top:0,left:0}},outerWidth:function(c){c=c||!1;let a=this.get(0);if(null!=a)return c?parseInt(a.offsetWidth)+parseInt(this.css("marginLeft"))+parseInt(this.css("marginRight")):parseInt(a.offsetWidth)},outerHeight:function(c){return c?parseInt(this.css("height"))+parseInt(this.css("marginTop"))+parseInt(this.css("marginBottom")):parseInt(this.css("height"))},width:function(){return this.outerWidth()},height:function(){return this.outerHeight()},on:function(){let c=arguments,
a=function(e,f){let g;if("mouseenter"==f.type||"mouseleave"==f.type||"hover"==f.type){var h=document.elementFromPoint(f.clientX,f.clientY);if(!h.matches(e[1]))for(;(h=h.parentElement)&&!h.matches(e[1]););null!=h&&(g=WPD.dom(h))}else g=WPD.dom(f.target).closest(e[1]);if(null!=g&&0<g.closest(this).length){h=[];h.push(f);if("undefined"!=typeof e[4])for(f=4;f<e.length;f++)h.push(e[f]);e[2].apply(g.get(0),h)}},b=function(e,f){let g=[];g.push(f);if("undefined"!=typeof e[3])for(f=3;f<e.length;f++)g.push(e[f]);
e[1].apply(this,g)},d=c[0].split(" ");for(let e=0;e<d.length;e++){let f=d[e];"string"==typeof c[1]?this.forEach(function(g){if(!WPD.dom._fn.hasEventListener(g,f,c[2])){let h=a.bind(g,c);g.addEventListener(f,h,c[3]);g._wpd_el="undefined"==typeof g._wpd_el?[]:g._wpd_el;g._wpd_el.push({type:f,selector:c[1],func:h,trigger:c[2],args:c[3]})}}):this.forEach(function(g){if(!WPD.dom._fn.hasEventListener(g,f,c[1])){let h=b.bind(g,c);g.addEventListener(f,h,c[2]);g._wpd_el="undefined"==typeof g._wpd_el?[]:g._wpd_el;
g._wpd_el.push({type:f,func:h,trigger:c[1],args:c[2]})}})}return this},off:function(c,a){this.forEach(function(b){if("undefined"!=typeof b._wpd_el&&0<b._wpd_el.length)if("undefined"===typeof c){let d;for(;d=b._wpd_el.pop();)b.removeEventListener(d.type,d.func,d.args);b._wpd_el=[]}else c.split(" ").forEach(function(d){if("undefined"==typeof a){let e;for(;e=b._wpd_el.pop();)b.removeEventListener(d,e.func,e.args);b._wpd_el=[]}else{let e=[];b._wpd_el.forEach(function(f){f.type==d&&f.trigger==a?b.removeEventListener(d,
f.func,f.args):e.push(f)});b._wpd_el=e}})});return this},offForced:function(){let c=this;this.forEach(function(a,b){let d=a.cloneNode(!0);a.parentNode.replaceChild(d,a);c.a[b]=d});return this},trigger:function(c,a,b,d){b=b||!1;d=d||!1;this.forEach(function(e){var f=!1;d&&"undefined"!=typeof jQuery&&"undefined"!=typeof jQuery._data&&"undefined"!=typeof jQuery._data(e,"events")&&"undefined"!=typeof jQuery._data(e,"events")[c]&&(jQuery(e).trigger(c,a),f=!0);!f&&b&&(f=new Event(c),f.detail=a,e.dispatchEvent(f));
if("undefined"!=typeof e._wpd_el)e._wpd_el.forEach(function(g){if(g.type==c){let h=new Event(c);g.trigger.apply(e,[h].concat(a))}});else{let g=!1,h=e;for(;;){h=h.parentElement;if(null==h)break;"undefined"!=typeof h._wpd_el&&h._wpd_el.forEach(function(k){if("undefined"!==typeof k.selector){var l=WPD.dom(h).find(k.selector);0<l.length&&0<=l.get().indexOf(e)&&k.type==c&&(l=new Event(c),k.trigger.apply(e,[l].concat(a)),g=!0)}});if(g)break}}});return this},clone:function(){let c=this.get(0);null!=c?(this.a=
[c.cloneNode(!0)],this.length=this.a.length):this.a=[];this.length=this.a.length;return this},remove:function(c){if("undefined"!=typeof c)return c.parentElement.removeChild(c);this.forEach(function(a){if(null!=a.parentElement)return a.parentElement.removeChild(a)});this.a=[];this.length=this.a.length;return null},detach:function(){let c=this,a=[];this.forEach(function(b){b=c.remove(b);null!=b&&a.push(b)});this.a=a;this.length=this.a.length;return this},prepend:function(c){"string"==typeof c&&(c=WPD.dom._fn.createElementsFromHTML(c));
c=Array.isArray(c)?c:[c];this.forEach(function(a){c.forEach(function(b){"undefined"!=typeof b.is_wpd_dom?b.forEach(function(d){a.insertBefore(d,a.children[0])}):a.insertBefore(b,a.children[0])})});return this},append:function(c){"string"==typeof c&&(c=WPD.dom._fn.createElementsFromHTML(c));c=Array.isArray(c)?c:[c];this.forEach(function(a){c.forEach(function(b){null!=b&&("undefined"!=typeof b.is_wpd_dom?b.forEach(function(d){a.appendChild(d)}):a.appendChild(b.cloneNode(!0)))})});return this},uuidv4:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(c){let a=16*Math.random()|0;return("x"==c?a:a&3|8).toString(16)})}},WPD.dom._fn={bodyTransformY:function(){if("undefined"!==typeof WebKitCSSMatrix){var c=window.getComputedStyle(document.body);if("undefined"!=typeof c.transform&&(c=new WebKitCSSMatrix(c.transform),"undefined"!=c.m42))return c.m42}return 0},hasFixedParent:function(c){if(0!=WPD.dom._fn.bodyTransformY())return!1;do if("fixed"==window.getComputedStyle(c).position)return!0;while(c=c.parentElement);return!1},hasEventListener:function(c,
a,b){if("undefined"==typeof c._wpd_el)return!1;for(let d=0;d<c._wpd_el.length;d++)if(c._wpd_el[d].trigger==b&&c._wpd_el[d].type==a)return!0;return!1},allDescendants:function(c){let a=[],b=this;Array.isArray(c)||(c=[c]);c.forEach(function(d){for(let e=0;e<d.childNodes.length;e++){let f=d.childNodes[e];a.push(f);a=a.concat(b.allDescendants(f))}});return a},createElementsFromHTML:function(c){let a=document.createElement("template");a.innerHTML=c.replace(/(\r\n|\n|\r)/gm,"");return Array.prototype.slice.call(a.content.childNodes)},
absolutePosition:function(c){if(!c.getClientRects().length)return{top:0,left:0};let a=c.getBoundingClientRect();c=c.ownerDocument.defaultView;return{top:a.top+c.pageYOffset,left:a.left+c.pageXOffset}},plugin:function(c,a){WPD.dom.fn[c]=function(b){return"undefined"!=typeof b&&a[b]?a[b].apply(this,Array.prototype.slice.call(arguments,1)):this.each(function(d){d["wpd_dom_"+c]=Object.create(a).init(b,d)})}}},WPD.dom.version=1;return 1<=arguments.length?WPD.dom.fn.$.apply(WPD.dom.fn,arguments):WPD.dom.fn};
WPD.dom();document.dispatchEvent(new Event("wpd-dom-core-loaded"))})();
(function(){WPD.dom.fn._animate={easing:{linear:function(c){return c},easeInOutQuad:function(c){return.5>c?2*c*c:1-Math.pow(-2*c+2,2)/2},easeOutQuad:function(c){return 1-(1-c)*(1-c)}}};WPD.dom.fn.animate=function(c,a,b){let d=this;a=a||200;b=b||"linear";this.forEach(function(e){let f,g=0,h,k={},l={},m,p,q;m=d.prop("_wpd_dom_animations");m=null==m?[]:m;!1===c?m.forEach(function(n){clearInterval(n)}):(q="undefined"!=typeof d._animate.easing[b]?d._animate.easing[b]:d._animate.easing.easeInOutQuad,Object.keys(c).forEach(function(n){-1<
n.indexOf("scroll")?k[n]=e[n]:k[n]=parseInt(window.getComputedStyle(e)[n]);l[n]=c[n]-k[n]}),f=a/1E3*60,p=setInterval(function(){g++;g>f?clearInterval(p):(h=q(g/f),Object.keys(l).forEach(function(n){-1<n.indexOf("scroll")?e[n]=k[n]+l[n]*h:e.style[n]=k[n]+l[n]*h+"px"}))},1E3/60),m.push(p),d.prop("_wpd_dom_animations",m))});return this};document.dispatchEvent(new Event("wpd-dom-animate-loaded"))})();
(function(){let c=WPD.dom;WPD.dom.fn.unhighlight=function(a){let b={className:"highlight",element:"span"};c.extend(b,a);return this.find(b.element+"."+b.className).each(function(){let d=this.parentNode;d.replaceChild(this.firstChild,this);d.normalize()})};WPD.dom.fn.highlight=function(a,b){function d(g,h,k,l,m){m=""==m?".exhghttt":m;if(3===g.nodeType){if(h=g.data.normalize("NFD").replace(/[\u0300-\u036f]/g,"").match(h))return k=document.createElement(k||"span"),k.className=l||"highlight",l=/\.|,|\s/.test(h[0].charAt(0))?
h.index+1:h.index,g=g.splitText(l),g.splitText(h[1].length),l=g.cloneNode(!0),k.appendChild(l),g.parentNode.replaceChild(k,g),1}else if(1===g.nodeType&&g.childNodes&&!/(script|style)/i.test(g.tagName)&&0< !c(g).closest(m).length&&(g.tagName!==k.toUpperCase()||g.className!==l))for(let p=0;p<g.childNodes.length;p++)p+=d(g.childNodes[p],h,k,l,m);return 0}let e={className:"highlight",element:"span",caseSensitive:!1,wordsOnly:!1,excludeParents:""};c.fn.extend(e,b);a.constructor===String&&(a=[a]);a=a.filter(function(g){return""!=
g});a.forEach(function(g,h,k){k[h].replace(/[-[\]{}()*+?.,\\^$|#\s]/g,"\\$&").normalize("NFD").replace(/[\u0300-\u036f]/g,"")});if(0==a.length)return this;b=e.caseSensitive?"":"i";a="("+a.join("|")+")";e.wordsOnly&&(a="(?:,|^|\\s)"+a+"(?:,|$|\\s)");let f=new RegExp(a,b);return this.each(function(g){d(g,f,e.element,e.className,e.excludeParents)})}})();
(function(){WPD.dom.fn.serialize=function(){let c=this.get(0);if(c&&"FORM"===c.nodeName){var a,b,d=[];for(a=c.elements.length-1;0<=a;--a)if(""!==c.elements[a].name)switch(c.elements[a].nodeName){case "INPUT":switch(c.elements[a].type){case "text":case "hidden":case "password":case "button":case "reset":case "submit":d.push(c.elements[a].name+"="+encodeURIComponent(c.elements[a].value));break;case "checkbox":case "radio":c.elements[a].checked&&d.push(c.elements[a].name+"="+encodeURIComponent(c.elements[a].value))}break;
case "TEXTAREA":d.push(c.elements[a].name+"="+encodeURIComponent(c.elements[a].value));break;case "SELECT":switch(c.elements[a].type){case "select-one":d.push(c.elements[a].name+"="+encodeURIComponent(c.elements[a].value));break;case "select-multiple":for(b=c.elements[a].options.length-1;0<=b;--b)c.elements[a].options[b].selected&&d.push(c.elements[a].name+"="+encodeURIComponent(c.elements[a].options[b].value))}break;case "BUTTON":switch(c.elements[a].type){case "reset":case "submit":case "button":d.push(c.elements[a].name+
"="+encodeURIComponent(c.elements[a].value))}}return d.join("&")}};WPD.dom.fn.serializeForAjax=function(c,a){let b=[],d;for(d in c)if(c.hasOwnProperty(d)){let e=a?a+"["+d+"]":d,f=c[d];b.push(null!==f&&"object"===typeof f?WPD.dom.fn.serializeForAjax(f,e):encodeURIComponent(e)+"="+encodeURIComponent(f))}return b.join("&")};document.dispatchEvent(new Event("wpd-dom-serialize-loaded"))})();
(function(){WPD.dom.fn.inViewPort=function(c,a){var b=this.get(0);let d;if(null==b)return!1;c="undefined"==typeof c?0:c;a="undefined"==typeof a?window:"string"==typeof a?document.querySelector(a):a;var e=b.getBoundingClientRect();b=e.top;let f=e.bottom,g=e.left,h=e.right;null==a&&(a=window);a===window?(e=window.innerWidth||0,d=window.innerHeight||0):(e=a.clientWidth,d=a.clientHeight,a=a.getBoundingClientRect(),b-=a.top,f-=a.top,g-=a.left,h-=a.left);c=~~Math.round(parseFloat(c));return 0>=h||g>=e?
!1:0<c?b>=c&&f<d-c:(0<f&&b<=d-c)|(0>=b&&f>c)};document.dispatchEvent(new Event("wpd-dom-viewport-loaded"))})();
(function(){WPD.dom.fn.ajax=function(c){c=this.extend({url:"",method:"GET",cors:"cors",data:{},success:null,fail:null,accept:"text/html",contentType:"application/x-www-form-urlencoded; charset=UTF-8"},c);if("cors"!=c.cors){var a="ajax_cb_"+this.uuidv4().replaceAll("-","");WPD.dom.fn[a]=function(){c.success.apply(this,arguments);delete WPD.dom.fn[c.data.fn]};c.data.callback="WPD.dom.fn."+a;c.data.fn=a;a=document.createElement("script");a.type="text/javascript";a.src=c.url+"?"+this.serializeForAjax(c.data);
a.onload=function(){this.remove()};document.body.appendChild(a)}else return a=new XMLHttpRequest,a.onreadystatechange=function(){null!=c.success&&4==this.readyState&&200==this.status&&c.success(this.responseText);null!=c.fail&&4==this.readyState&&400<=this.status&&c.fail(this)},a.open(c.method.toUpperCase(),c.url,!0),a.setRequestHeader("Content-type",c.contentType),a.setRequestHeader("Accept",c.accept),a.send(this.serializeForAjax(c.data)),a};document.dispatchEvent(new Event("wpd-dom-xhttp-loaded"))})();
window.WPD=window.WPD||{};
window.WPD.Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(c){let a="";let b,d,e,f,g,h=0;for(c=this._utf8_encode(c);h<c.length;){var k=c.charCodeAt(h++);b=c.charCodeAt(h++);d=c.charCodeAt(h++);e=k>>2;k=(k&3)<<4|b>>4;f=(b&15)<<2|d>>6;g=d&63;isNaN(b)?f=g=64:isNaN(d)&&(g=64);a=a+this._keyStr.charAt(e)+this._keyStr.charAt(k)+this._keyStr.charAt(f)+this._keyStr.charAt(g)}return a},decode:function(c){let a="";let b,d,e,f=0;for(c=c.replace(/[^A-Za-z0-9\+\/=]/g,
"");f<c.length;){var g=this._keyStr.indexOf(c.charAt(f++));var h=this._keyStr.indexOf(c.charAt(f++));d=this._keyStr.indexOf(c.charAt(f++));e=this._keyStr.indexOf(c.charAt(f++));g=g<<2|h>>4;h=(h&15)<<4|d>>2;b=(d&3)<<6|e;a+=String.fromCharCode(g);64!=d&&(a+=String.fromCharCode(h));64!=e&&(a+=String.fromCharCode(b))}return a=this._utf8_decode(a)},_utf8_encode:function(c){c=c.replace(/\r\n/g,"\n");let a="";for(let b=0;b<c.length;b++){let d=c.charCodeAt(b);128>d?a+=String.fromCharCode(d):(127<d&&2048>
d?a+=String.fromCharCode(d>>6|192):(a+=String.fromCharCode(d>>12|224),a+=String.fromCharCode(d>>6&63|128)),a+=String.fromCharCode(d&63|128))}return a},_utf8_decode:function(c){let a="",b=0,d,e,f;for(;b<c.length;)d=c.charCodeAt(b),128>d?(a+=String.fromCharCode(d),b++):191<d&&224>d?(e=c.charCodeAt(b+1),a+=String.fromCharCode((d&31)<<6|e&63),b+=2):(e=c.charCodeAt(b+1),f=c.charCodeAt(b+2),a+=String.fromCharCode((d&15)<<12|(e&63)<<6|f&63),b+=3);return a}};
(function(){window.WPD=window.WPD||{};WPD.Hooks=WPD.Hooks||{};let c=WPD.Hooks;c.filters=c.filters||{};c.addFilter=function(a,b,d,e){c.filters[a]=c.filters[a]||[];c.filters[a].push({priority:"undefined"===typeof d?10:d,scope:"undefined"===typeof e?null:e,callback:b})};c.removeFilter=function(a,b){"undefined"!=typeof c.filters[a]&&("undefined"==typeof b?c.filters[a]=[]:c.filters[a].forEach(function(d,e){d.callback===b&&c.filters[a].splice(e,1)}))};c.applyFilters=function(a){let b=[],d=Array.prototype.slice.call(arguments),
e=arguments[1];"undefined"!==typeof c.filters[a]&&0<c.filters[a].length&&(c.filters[a].forEach(function(f){b[f.priority]=b[f.priority]||[];b[f.priority].push({scope:f.scope,callback:f.callback})}),d.splice(0,2),b.forEach(function(f){f.forEach(function(g){e=g.callback.apply(g.scope,[e].concat(d))})}));return e}})();window.WPD=window.WPD||{};
window.WPD.intervalUntilExecute=function(c,a,b,d){let e,f=0,g="function"===typeof a?a():a;b="undefined"==typeof b?100:b;d="undefined"==typeof d?50:d;if(!1===g)e=setInterval(function(){g="function"===typeof a?a():a;f++;if(f>d)return clearInterval(e),!1;if(!1!==g)return clearInterval(e),c(g)},b);else return c(g)};
(function(){window.WPD="undefined"!==typeof window.WPD?window.WPD:{};window.WPD.ajaxsearchlite=new function(){this.prevState=null;this.firstIteration=!0;this.helpers={};this.plugin={};this.addons={addons:[],add:function(c){-1==this.addons.indexOf(c)&&(c=this.addons.push(c),this.addons[c-1].init())},remove:function(c){this.addons.filter(function(a){return a.name==c?("undefined"!=typeof a.destroy&&a.destroy(),!1):!0})}}}})();WPD.dom._fn.plugin("ajaxsearchlite",window.WPD.ajaxsearchlite.plugin);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{autocompleteGoogleOnly:function(){let a=this,b=a.n.text.val();if(""==a.n.text.val())a.n.textAutocomplete.val("");else{var d=a.n.textAutocomplete.val();if(""==d||0!=d.indexOf(b)){a.n.textAutocomplete.val("");var e=a.o.autocomplete.lang;["wpml_lang","polylang_lang","qtranslate_lang"].forEach(function(f){0<c('input[name="'+f+'"]',a.n.searchsettings).length&&1<c('input[name="'+f+'"]',a.n.searchsettings).val().length&&(e=c('input[name="'+f+'"]',
a.n.searchsettings).val())});a.n.text.val().length>=a.o.autocomplete.trigger_charcount&&c.fn.ajax({url:"https://clients1.google.com/complete/search",cors:"no-cors",data:{q:b,hl:e,nolabels:"t",client:"hp",ds:""},success:function(f){0<f[1].length&&(f=f[1][0][0].replace(/(<([^>]+)>)/ig,""),f=c("<textarea />").html(f).text(),f=f.substr(b.length),a.n.textAutocomplete.val(b+f),a.fixAutocompleteScrollLeft())}})}}},fixAutocompleteScrollLeft:function(){this.n.textAutocomplete.get(0).scrollLeft=this.n.text.get(0).scrollLeft}})})(WPD.dom);
(function(c){let a=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{setFilterStateInput:function(b){let d=this;"undefined"==typeof b&&(b=65);let e=function(){JSON.stringify(d.originalFormData)!=JSON.stringify(a.formData(c("form",d.n.searchsettings)))?d.n.searchsettings.find("input[name=filters_initial]").val(0):d.n.searchsettings.find("input[name=filters_initial]").val(1)};0==b?e():setTimeout(function(){e()},b)}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{gaPageview:function(a){let b=this.gaGetTrackingID();if("undefined"==typeof ASL.analytics||"pageview"!=ASL.analytics.method)return!1;if(""!=ASL.analytics.string){let d="function"==typeof __gaTracker?__gaTracker:"function"==typeof ga?ga:!1,e="function"==typeof gtag?gtag:!1;window.location.origin||(window.location.origin=window.location.protocol+"//"+window.location.hostname+(window.location.port?":"+window.location.port:""));let f=this.o.homeurl.replace(window.location.origin,
"");!1!==e?!1!==b&&e("config",b,{page_path:f+ASL.analytics.string.replace("{asl_term}",a)}):!1!==d&&(!1!==b&&d("create",b,"auto"),d("send","pageview",{page:f+ASL.analytics.string.replace("{asl_term}",a),title:"Ajax Search"}))}},gaEvent:function(a,b){let d=this.gaGetTrackingID();if("undefined"==typeof ASL.analytics||"event"!=ASL.analytics.method)return!1;let e="function"==typeof gtag?gtag:!1,f="function"==typeof window.__gaTracker?window.__gaTracker:"function"==typeof window.ga?window.ga:!1;if(!1===
e&&!1===f)return!1;if("undefined"!=typeof ASL.analytics.event[a]&&1==ASL.analytics.event[a].active){let g={search_id:this.o.id,search_name:this.o.name,phrase:this.n.text.val(),option_name:"",option_value:"",result_title:"",result_url:"",results_count:""},h={event_category:ASL.analytics.event[a].category,event_label:ASL.analytics.event[a].label,value:ASL.analytics.event[a].value};b=c.fn.extend(g,b);Object.keys(b).forEach(function(k){let l=b[k];l=String(l).replace(/[\s\n\r]+/g," ").trim();Object.keys(h).forEach(function(m){h[m]=
h[m].replace(new RegExp("{"+k+"}","gmi"),l)})});!1===e?!1!==d?d.forEach(function(k){f("create",k,"auto");f("send","event",h.event_category,ASL.analytics.event[a].action,h.event_label,h.value)}):f("send","event",h.event_category,ASL.analytics.event[a].action,h.event_label,h.value):!1!==d?d.forEach(function(k){h.send_to=k;e("event",ASL.analytics.event[a].action,h)}):e("event",ASL.analytics.event[a].action,h)}},gaGetTrackingID:function(){if("undefined"==typeof ASL.analytics)return!1;if("undefined"!=
typeof ASL.analytics.tracking_id&&""!=ASL.analytics.tracking_id)return[ASL.analytics.tracking_id];if(!1===("function"==typeof window.gtag?window.gtag:!1)&&"undefined"!=typeof window.ga&&"undefined"!=typeof window.ga.getAll){let a=[];window.ga.getAll().forEach(function(b){a.push(b.get("trackingId"))});return 0<a.length?a:!1}return!1}})})(WPD.dom);
(function(c){let a=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{liveLoad:function(b,d,e,f){function g(m){m=a.Hooks.applyFilters("asl/live_load/raw_data",m,l);var p=new DOMParser;let q=p.parseFromString(m,"text/html"),n=c(q);l.o.statistics&&l.stat_addKeyword(l.o.id,l.n.text.val());if(""!=m&&0<n.length&&0<n.find(b).length){m=m.replace(/&asl_force_reset_pagination=1/gmi,"");m=m.replace(/%26asl_force_reset_pagination%3D1/gmi,"");m=m.replace(/&#038;asl_force_reset_pagination=1/gmi,
"");a.isSafari()&&(m=m.replace(/srcset/gmi,"nosrcset"));m=a.Hooks.applyFilters("asl/live_load/html",m,l.o.id,l.o.iid);m=a.wp_hooks_apply_filters("asl/live_load/html",m,l.o.id,l.o.iid);n=c(p.parseFromString(m,"text/html"));p=n.find(b).get(0);p=a.Hooks.applyFilters("asl/live_load/replacement_node",p,l,k.get(0),m);null!=p&&k.get(0).parentNode.replaceChild(p,k.get(0));k=c(b).first();e&&(document.title=q.title,history.pushState({},null,d));c(b).first().find(".woocommerce-ordering").on("change","select.orderby",
function(){c(this).closest("form").trigger("submit")});if(1==l.o.singleHighlight)c(b).find("a").on("click",function(){localStorage.removeItem("asl_phrase_highlight");""!=a.unqoutePhrase(l.n.text.val())&&localStorage.setItem("asl_phrase_highlight",JSON.stringify({phrase:a.unqoutePhrase(l.n.text.val())}))});a.Hooks.applyFilters("asl/live_load/finished",d,l,b,k.get(0));ASL.initialize();l.lastSuccesfulSearch=c("form",l.n.searchsettings).serialize()+l.n.text.val().trim();l.lastSearchData=m}l.n.s.trigger("asl_search_end",
[l.o.id,l.o.iid,l.n.text.val(),m],!0,!0);let r,t;null==(t=(r=l).gaEvent)||t.call(r,"search_end",{results_count:"unknown"});let u,v;null==(v=(u=l).gaPageview)||v.call(u,l.n.text.val());l.hideLoader();k.css("opacity",1);l.searching=!1;""!=l.n.text.val()&&l.n.proclose.css({display:"block"})}if("body"==b||"html"==b)return console.log("Ajax Search Pro: Do not use html or body as the live loader selector."),!1;""==ASL.pageHTML&&"undefined"===typeof ASL._ajax_page_html&&(ASL._ajax_page_html=!0,c.fn.ajax({url:location.href,
method:"GET",success:function(m){ASL.pageHTML=m},dataType:"html"}));e="undefined"==typeof e?!0:e;f="undefined"==typeof f?!1:f;let h=".search-content #content #Content div[role=main] main[role=main] div.theme-content div.td-ss-main-content main.l-content #primary".split(" ");"#main"!=b&&h.unshift("#main");if(1>c(b).length&&(h.forEach(function(m){if(0<c(m).length)return b=m,!1}),1>c(b).length))return console.log("Ajax Search Lite: The live search selector does not exist on the page."),!1;b=a.Hooks.applyFilters("asl/live_load/selector",
b,this);let k=c(b).first(),l=this;l.searchAbort();k.css("opacity",.4);a.Hooks.applyFilters("asl/live_load/start",d,l,b,k.get(0));f||1!=l.n.searchsettings.find("input[name=filters_initial]").val()||""!=l.n.text.val()?(l.searching=!0,l.post=c.fn.ajax({url:d,method:"GET",success:function(m){g(m)},dataType:"html",fail:function(m){k.css("opacity",1);m.aborted||(k.html("This request has failed. Please check your connection."),l.hideLoader(),l.searching=!1,l.n.proclose.css({display:"block"}))}})):window.WPD.intervalUntilExecute(function(){g(ASL.pageHTML)},
function(){return""!=ASL.pageHTML})},getCurrentLiveURL:function(){var b="asl_ls="+a.nicePhrase(this.n.text.val());let d="&",e=window.location.href;e=-1<e.indexOf("asl_ls=")?e.slice(0,e.indexOf("asl_ls=")):e;e=-1<e.indexOf("asl_ls&")?e.slice(0,e.indexOf("asl_ls&")):e;e=-1<e.indexOf("p_asid=")?e.slice(0,e.indexOf("p_asid=")):e;e=-1<e.indexOf("asl_")?e.slice(0,e.indexOf("asl_")):e;-1===e.indexOf("?")&&(d="?");b=e+d+b+"&asl_active=1&asl_force_reset_pagination=1&p_asid="+this.o.id+"&p_asl_data=1&"+c("form",
this.n.searchsettings).serialize();return b=b.replace("?&","?")}})})(WPD.dom);(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{showLoader:function(){this.n.proloading.css({display:"block"})},hideLoader:function(){this.n.proloading.css({display:"none"});this.n.results.css("display","")}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{fixClonedSelf:function(){let a=this.o.iid,b=this.o.rid;for(;!ASL.instances.set(this)&&!(++this.o.iid,50<this.o.iid););a!=this.o.iid&&(this.o.rid=this.o.id+"_"+this.o.iid,this.n.search.get(0).id="ajaxsearchlite"+this.o.rid,this.n.search.removeClass("asl_m_"+b).addClass("asl_m_"+this.o.rid),this.n.searchsettings.get(0).id=this.n.searchsettings.get(0).id.replace("settings"+b,"settings"+this.o.rid),this.n.searchsettings.hasClass("asl_s_"+b)?this.n.searchsettings.removeClass("asl_s_"+
b).addClass("asl_s_"+this.o.rid).data("instance",this.o.iid):this.n.searchsettings.removeClass("asl_sb_"+b).addClass("asl_sb_"+this.o.rid).data("instance",this.o.iid),this.n.resultsDiv.get(0).id=this.n.resultsDiv.get(0).id.replace("prores"+b,"prores"+this.o.rid),this.n.resultsDiv.removeClass("asl_r_"+b).addClass("asl_r_"+this.o.rid).data("instance",this.o.iid),this.n.container.find(".asl_init_data").data("instance",this.o.iid),this.n.container.find(".asl_init_data").get(0).id=this.n.container.find(".asl_init_data").get(0).id.replace("asl_init_id_"+
b,"asl_init_id_"+this.o.rid),this.n.prosettings.data("opened",0))},destroy:function(){let a=this;Object.keys(a.n).forEach(function(b){a.n[b].off()});a.n.searchsettings.remove();a.n.resultsDiv.remove();a.n.trythis.remove();a.n.search.remove();a.n.container.remove();a.documentEventHandlers.forEach(function(b){c(b.node).off(b.event,b.handler)})}})})(WPD.dom);
(function(c){let a=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{isRedirectToFirstResult:function(){return(0<c(".asl_res_url",this.n.resultsDiv).length||0<c(".asl_es_"+this.o.id+" a").length||this.o.resPage.useAjax&&0<c(this.o.resPage.selector+"a").length)&&(1==this.o.redirectOnClick&&"click"==this.ktype&&"first_result"==this.o.trigger.click||1==this.o.redirectOnEnter&&("input"==this.ktype||"keyup"==this.ktype)&&13==this.keycode&&"first_result"==this.o.trigger.return)},
doRedirectToFirstResult:function(){let b,d;b="click"==this.ktype?this.o.trigger.click_location:this.o.trigger.return_location;0<c(".asl_res_url",this.n.resultsDiv).length?d=c(c(".asl_res_url",this.n.resultsDiv).get(0)).attr("href"):0<c(".asl_es_"+this.o.id+" a").length?d=c(c(".asl_es_"+this.o.id+" a").get(0)).attr("href"):this.o.resPage.useAjax&&0<c(this.o.resPage.selector+"a").length&&(d=c(c(this.o.resPage.selector+"a").get(0)).attr("href"));""!=d&&("same"==b?location.href=d:a.openInNewTab(d),this.hideLoader(),
this.hideResults());return!1},doRedirectToResults:function(b){let d;d="click"==b?this.o.trigger.click_location:this.o.trigger.return_location;b=this.getRedirectURL(b);if(this.o.overridewpdefault){if(1==this.o.resPage.useAjax)return this.hideResults(),this.liveLoad(this.o.resPage.selector,b),this.showLoader(),0==this.o.blocking&&this.hideSettings(),!1;"post"==this.o.override_method?a.submitToUrl(b,"post",{asl_active:1,p_asl_data:c("form",this.n.searchsettings).serialize()},d):"same"==d?location.href=
b:a.openInNewTab(b)}else a.submitToUrl(b,"post",{np_asl_data:c("form",this.n.searchsettings).serialize()},d);this.n.proloading.css("display","none");this.hideLoader();this.hideResults();this.searchAbort()},getRedirectURL:function(b){b="click"==("undefined"!==typeof b?b:"enter")?this.o.trigger.click:this.o.trigger.return;"results_page"==b||"ajax_search"==b?b="?s="+a.nicePhrase(this.n.text.val()):"woo_results_page"==b?b="?post_type=product&s="+a.nicePhrase(this.n.text.val()):(b=this.o.trigger.redirect_url,
b=b.replace(/{phrase}/g,a.nicePhrase(this.n.text.val())));1<this.o.homeurl.indexOf("?")&&0===b.indexOf("?")&&(b=b.replace("?","&"));if(this.o.overridewpdefault&&"post"!=this.o.override_method){let d="&";-1===this.o.homeurl.indexOf("?")&&-1===b.indexOf("?")&&(d="?");b=b+d+"asl_active=1&p_asl_data=1&"+c("form",this.n.searchsettings).serialize();b=this.o.homeurl+b}else b=this.o.homeurl+b;b=b.replace("https://","https:///");b=b.replace("http://","http:///");b=b.replace(/\/\//g,"/");b=a.Hooks.applyFilters("asl/redirect/url",
b,this.o.id,this.o.iid);return b=a.wp_hooks_apply_filters("asl/redirect/url",b,this.o.id,this.o.iid)}})})(WPD.dom);
(function(c){let a=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{showResults:function(){let b=this;b.createVerticalScroll();b.showVerticalResults();b.hideLoader();b.n.proclose.css({display:"block"});null!=b.n.showmore&&(0<b.n.items.length?b.n.showmore.css({display:"block"}):b.n.showmore.css({display:"none"}));"undefined"!=typeof WPD.lazy&&setTimeout(function(){WPD.lazy(".asl_lazy")},100);b.is_scroll&&"undefined"!==typeof b.scroll.recalculate&&setTimeout(function(){b.scroll.recalculate()},
500);b.resultsOpened=!0},hideResults:function(b){let d=this;b="undefined"==typeof b?!0:b;if(!d.resultsOpened)return!1;d.n.resultsDiv.removeClass(d.resAnim.showClass).addClass(d.resAnim.hideClass);setTimeout(function(){d.n.resultsDiv.css(d.resAnim.hideCSS)},d.resAnim.duration);d.n.proclose.css({display:"none"});a.isMobile()&&b&&document.activeElement.blur();d.resultsOpened=!1;d.n.s.trigger("asl_results_hide",[d.o.id,d.o.iid],!0,!0)},showResultsBox:function(){this.n.s.trigger("asl_results_show",[this.o.id,
this.o.iid],!0,!0);this.n.resultsDiv.css({display:"block",height:"auto"});this.n.resultsDiv.css(this.resAnim.showCSS);this.n.resultsDiv.removeClass(this.resAnim.hideClass).addClass(this.resAnim.showClass);this.fixResultsPosition(!0)},scrollToResults:function(){var b=Math.floor(.1*window.innerHeight);if(this.resultsOpened&&1==this.o.scrollToResults.enabled&&!this.n.resultsDiv.inViewPort(b)){b="hover"==this.o.resultsposition?this.n.probox.offset().top-20:this.n.resultsDiv.offset().top-20;b+=this.o.scrollToResults.offset;
var d=c("#wpadminbar");0<d.length&&(b-=d.height());window.scrollTo({top:0>b?0:b,behavior:"smooth"})}}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{showVerticalResults:function(){this.showResultsBox();if(0<this.n.items.length){let a=this.n.items.length<this.o.itemscount?this.n.items.length:this.o.itemscount;a=0>=a?9999:a;let b=c(".asl_group_header",this.n.resultsDiv);if(0==this.o.itemscount||this.n.items.length<=this.o.itemscount)this.n.results.css({height:"auto"});else if(1>this.call_num&&this.n.results.css({height:"30px"}),1>this.call_num){let d=0,e=0,f=0,g=0;this.n.items.forEach(function(){e+=
c(this).outerHeight(!0);c(this).outerHeight(!0)>g&&(g=c(this).outerHeight(!0));d++});f=g*a;f>e&&(f=e);d=1>d?1:d;e=e/d*a;0<b.length&&b.forEach(function(h,k){h=Array.prototype.slice.call(h.parentNode.children).indexOf(h);h-k-Math.floor(h/3)<a&&(f+=c(this).outerHeight(!0))});this.n.results.css({height:f+"px"})}this.n.items.last().addClass("asl_last_item");this.n.results.find(".asl_group_header").prev(".item").addClass("asl_last_item");1==this.o.highlight&&c("div.item",this.n.resultsDiv).highlight(this.n.text.val().split(" "),
{element:"span",className:"highlighted",wordsOnly:this.o.highlightWholewords})}this.resize();0==this.n.items.length&&this.n.results.css({height:"auto"});this.n.results.css({overflowY:"auto"});(this.is_scroll&&"undefined"!==typeof this.scroll.recalculate?c(this.scroll.getScrollElement()):this.n.results).get(0).scrollTop=0;this.fixResultsPosition(!0);this.searching=!1}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{createVerticalScroll:function(){let a=this.n.results;0<this.o.itemscount&&this.is_scroll&&"undefined"===typeof this.scroll.recalculate&&(this.scroll=new asp_SimpleBar(this.n.results.get(0),{direction:c("body").hasClass("rtl")?"rtl":"ltr",autoHide:!0}),a=a.add(this.scroll.getScrollElement()));a.on("scroll",function(){document.dispatchEvent(new Event("wpd-lazy-trigger"))})}})})(WPD.dom);
(function(c){let a=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{searchAbort:function(){null!=this.post&&this.post.abort()},searchWithCheck:function(b){let d=this;"undefined"==typeof b&&(b=50);d.n.text.val().length<d.o.charcount||(d.searchAbort(),clearTimeout(d.timeouts.searchWithCheck),d.timeouts.searchWithCheck=setTimeout(function(){d.search()},b))},search:function(){let b=this;if(!(b.n.text.val().length<b.o.charcount)){b.searching=!0;b.n.proloading.css({display:"block"});
b.n.proclose.css({display:"none"});var d={action:"ajaxsearchlite_search",aslp:b.n.text.val(),asid:b.o.id,options:c("form",b.n.searchsettings).serialize()};d=a.Hooks.applyFilters("asl/search/data",d);d=a.wp_hooks_apply_filters("asl/search/data",d);if(JSON.stringify(d)===JSON.stringify(b.lastSearchData))return b.resultsOpened||b.showResults(),b.hideLoader(),b.isRedirectToFirstResult()&&b.doRedirectToFirstResult(),!1;var e;null==(e=b.gaEvent)||e.call(b,"search_start");0<c(".asl_es_"+b.o.id).length?b.liveLoad(".asl_es_"+
b.o.id,b.getCurrentLiveURL(),!1):b.o.resPage.useAjax?b.liveLoad(b.o.resPage.selector,b.getRedirectURL()):b.post=c.fn.ajax({url:ASL.ajaxurl,method:"POST",data:d,success:function(f){f=f.replace(/^\s*[\r\n]/gm,"");f=f.match(/!!ASLSTART!!(.*[\s\S]*)!!ASLEND!!/)[1];f=a.Hooks.applyFilters("asl/search/html",f);f=a.wp_hooks_apply_filters("asl/search/html",f);b.n.resdrg.html("");b.n.resdrg.html(f);c(".asl_keyword",b.n.resdrg).on("click",function(){b.n.text.val(c(this).html());c("input.orig",b.n.container).val(c(this).html()).trigger("keydown");
c("form",b.n.container).trigger("submit","ajax");b.search()});b.n.items=c(".item",b.n.resultsDiv);let g;null==(g=b.gaEvent)||g.call(b,"search_end",{results_count:b.n.items.length});let h;null==(h=b.gaPageview)||h.call(b,b.n.text.val());if(b.isRedirectToFirstResult())return b.doRedirectToFirstResult(),!1;b.hideLoader();b.showResults();b.scrollToResults();b.lastSuccesfulSearch=c("form",b.n.searchsettings).serialize()+b.n.text.val().trim();b.lastSearchData=d;0==b.n.items.length?null!=b.n.showmore&&b.n.showmore.css("display",
"none"):null!=b.n.showmore&&(b.n.showmore.css("display","block"),c("a",b.n.showmore).off(),c("a",b.n.showmore).on("click",function(){var k=b.o.trigger.click_location;k="results_page"==k?"?s="+a.nicePhrase(b.n.text.val()):"woo_results_page"==k?"?post_type=product&s="+a.nicePhrase(b.n.text.val()):b.o.trigger.redirect_url.replace("{phrase}",a.nicePhrase(b.n.text.val()));b.o.overridewpdefault?"post"==b.o.override_method?a.submitToUrl(b.o.homeurl+k,"post",{asl_active:1,p_asl_data:c("form",b.n.searchsettings).serialize()}):
location.href=b.o.homeurl+k+"&asl_active=1&p_asid="+b.o.id+"&p_asl_data=1&"+c("form",b.n.searchsettings).serialize():a.submitToUrl(b.o.homeurl+k,"post",{np_asl_data:c("form",b.n.searchsettings).serialize()})}))},fail:function(f){f.aborted||(b.n.resdrg.html(""),b.n.resdrg.html('<div class="asl_nores">The request failed. Please check your connection! Status: '+f.status+"</div>"),b.n.items=c(".item",b.n.resultsDiv),b.hideLoader(),b.showResults(),b.scrollToResults())}})}}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{showSettings:function(){let a=this;a.n.searchsettings.css(a.settAnim.showCSS);a.n.searchsettings.removeClass(a.settAnim.hideClass).addClass(a.settAnim.showClass);null==a.settScroll&&a.is_scroll&&(a.settScroll=[],c(".asl_sett_scroll",a.n.searchsettings).forEach(function(b,d){let e=this;setTimeout(function(){a.settScroll[d]=new asp_SimpleBar(c(e).get(0),{direction:c("body").hasClass("rtl")?"rtl":"ltr",autoHide:!0})},20)}));a.n.prosettings.data("opened",
1);a.fixSettingsPosition(!0)},hideSettings:function(){let a=this;a.n.searchsettings.removeClass(a.settAnim.showClass).addClass(a.settAnim.hideClass);setTimeout(function(){a.n.searchsettings.css(a.settAnim.hideCSS)},a.settAnim.duration);a.n.prosettings.data("opened",0)}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.helpers,{Hooks:window.WPD.Hooks,deviceType:function(){let a=window.innerWidth;return 640>=a?"phone":1024>=a?"tablet":"desktop"},detectIOS:function(){return"undefined"!=typeof window.navigator&&"undefined"!=typeof window.navigator.userAgent?null!=window.navigator.userAgent.match(/(iPod|iPhone|iPad)/):!1},detectIE:function(){var a=window.navigator.userAgent;let b=a.indexOf("MSIE ");a=a.indexOf("Trident/");return 0<b||0<a?!0:!1},isMobile:function(){try{return document.createEvent("TouchEvent"),
!0}catch(a){return!1}},isTouchDevice:function(){return"ontouchstart"in window},isSafari:function(){return/^((?!chrome|android).)*safari/i.test(navigator.userAgent)},whichjQuery:function(a){let b=!1;"undefined"!=typeof window.$&&("undefined"===typeof a?b=window.$:"undefined"!=typeof window.$.fn[a]&&(b=window.$));!1===b&&"undefined"!=typeof window.jQuery&&(b=window.jQuery,"undefined"===typeof a?b=window.jQuery:"undefined"!=typeof window.jQuery.fn[a]&&(b=window.jQuery));return b},formData:function(a,
b){let d=this,e=a.find("input,textarea,select,button").get();if(1===arguments.length)return b={},e.forEach(function(f){f.name&&!f.disabled&&(f.checked||/select|textarea/i.test(f.nodeName)||/text/i.test(f.type)||c(f).hasClass("hasDatepicker")||c(f).hasClass("asl_slider_hidden"))&&(void 0==b[f.name]&&(b[f.name]=[]),c(f).hasClass("hasDatepicker")?b[f.name].push(c(f).parent().find(".asl_datepicker_hidden").val()):b[f.name].push(c(f).val()))}),JSON.stringify(b);"object"!=typeof b&&(b=JSON.parse(b));e.forEach(function(f){if(f.name)if(b[f.name]){let g=
b[f.name],h=c(f);"[object Array]"!==Object.prototype.toString.call(g)&&(g=[g]);if("checkbox"==f.type||"radio"==f.type){let k=h.val(),l=!1;for(let m=0;m<g.length;m++)if(g[m]==k){l=!0;break}h.prop("checked",l)}else h.val(g[0]),(c(f).hasClass("asl_gochosen")||c(f).hasClass("asl_goselect2"))&&WPD.intervalUntilExecute(function(k){k(f).trigger("change.asl_select2")},function(){return d.whichjQuery("asl_select2")},50,3),c(f).hasClass("hasDatepicker")&&WPD.intervalUntilExecute(function(k){let l=g[0],m=k(h.get(0)).datepicker("option",
"dateFormat");k(h.get(0)).datepicker("option","dateFormat","yy-mm-dd");k(h.get(0)).datepicker("setDate",l);k(h.get(0)).datepicker("option","dateFormat",m);k(h.get(0)).trigger("selectnochange")},function(){return d.whichjQuery("datepicker")},50,3)}else"checkbox"!=f.type&&"radio"!=f.type||c(f).prop("checked",!1)});return a},submitToUrl:function(a,b,d,e){let f;f=c('<form style="display: none;" />');f.attr("action",a);f.attr("method",b);c("body").append(f);"undefined"!==typeof d&&null!==d&&Object.keys(d).forEach(function(g){let h=
d[g],k=c('<input type="hidden" />');k.attr("name",g);k.attr("value",h);f.append(k)});"undefined"!=typeof e&&"new"==e&&f.attr("target","_blank");f.get(0).submit()},openInNewTab:function(a){Object.assign(document.createElement("a"),{target:"_blank",href:a}).click()},isScrolledToBottom:function(a,b){return a.scrollHeight-a.scrollTop-c(a).outerHeight()<b},getWidthFromCSSValue:function(a,b){a+="";a=-1<a.indexOf("px")?parseInt(a,10):-1<a.indexOf("%")?"undefined"!=typeof b&&null!=b?Math.floor(parseInt(a,
10)/100*b):parseInt(a,10):parseInt(a,10);return 100>a?100:a},nicePhrase:function(a){return encodeURIComponent(a).replace(/%20/g,"+")},unqoutePhrase:function(a){return a.replace(/["']/g,"")},decodeHTMLEntities:function(a){let b=document.createElement("div");a&&"string"===typeof a&&(a=a.replace(/<script[^>]*>([\S\s]*?)<\/script>/gmi,""),a=a.replace(/<\/?\w(?:[^"'>]|"[^"]*"|'[^']*')*>/gmi,""),b.innerHTML=a,a=b.textContent,b.textContent="");return a},isScrolledToRight:function(a){return a.scrollWidth-
c(a).outerWidth()===a.scrollLeft},isScrolledToLeft:function(a){return 0===a.scrollLeft},wp_hooks_apply_filters:function(){return"undefined"!=typeof wp&&"undefined"!=typeof wp.hooks&&"undefined"!=typeof wp.hooks.applyFilters?wp.hooks.applyFilters.apply(null,arguments):"undefined"!=typeof arguments[1]?arguments[1]:!1}})})(WPD.dom);
(function(c){let a=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{detectAndFixFixedPositioning:function(){let b=!1,d=this.n.search.get(0);for(;d;)if(d=d.parentElement,null!=d&&"fixed"==window.getComputedStyle(d).position){b=!0;break}b||"fixed"==this.n.search.css("position")?("absolute"==this.n.resultsDiv.css("position")&&this.n.resultsDiv.css("position","fixed"),this.o.blocking||this.n.searchsettings.css("position","fixed")):("fixed"==this.n.resultsDiv.css("position")&&
this.n.resultsDiv.css("position","absolute"),this.o.blocking||this.n.searchsettings.css("position","absolute"))},fixResultsPosition:function(b){b="undefined"==typeof b?!1:b;var d=this.n.resultsDiv.css("position");if("fixed"==d||"absolute"==d)if(1==b||"visible"==this.n.resultsDiv.css("visibility"))if(b=this.n.search.offset(),"undefined"!=typeof b){let e=0;d="phone"==a.deviceType()?this.o.results.width_phone:"tablet"==a.deviceType()?this.o.results.width_tablet:this.o.results.width;"auto"==d&&(d=240>
this.n.search.outerWidth()?240:this.n.search.outerWidth());this.n.resultsDiv.css("width",isNaN(d)?d:d+"px");"right"==this.o.resultsSnapTo?e=this.n.resultsDiv.outerWidth()-this.n.search.outerWidth():"center"==this.o.resultsSnapTo&&(e=Math.floor((this.n.resultsDiv.outerWidth()-parseInt(this.n.search.outerWidth()))/2));this.n.resultsDiv.css({top:b.top+this.n.search.outerHeight(!0)-0+"px",left:b.left-e+"px"})}},fixSettingsPosition:function(b){if((1==("undefined"==typeof b?!1:b)||0!=this.n.prosettings.data("opened"))&&
1!=this.o.blocking){let e;this.n.searchsettings.css("position");this.fixSettingsWidth();var d="none"!=this.n.prosettings.css("display")?this.n.prosettings:this.n.promagnifier;e=d.offset();b=e.top+d.height()-2+"px";d=("left"==this.o.settingsimagepos?e.left:e.left+d.width()-this.n.searchsettings.width())+"px";this.n.searchsettings.css({display:"block",top:b,left:d})}},fixSettingsWidth:function(){},hideOnInvisibleBox:function(){if(1==this.o.detectVisibility&&!this.n.search.hasClass("hiddend")&&(this.n.search.is(":hidden")||
!this.n.search.is(":visible"))){let b;null==(b=this.hideSettings)||b.call(this);this.hideResults()}}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initAutocompleteEvent:function(){let a=this;1==a.o.autocomplete.enabled&&(a.n.text.on("keyup",function(b){a.keycode=b.keyCode||b.which;a.ktype=b.type;let d=39;c("body").hasClass("rtl")&&(d=37);a.keycode==d&&""!=a.n.textAutocomplete.val()?(b.preventDefault(),a.n.text.val(a.n.textAutocomplete.val()),null!=a.post&&a.post.abort(),a.search()):(null!=a.postAuto&&a.postAuto.abort(),a.autocompleteGoogleOnly())}),a.n.text.on("keyup mouseup input blur select",
function(){a.fixAutocompleteScrollLeft()}))}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initMagnifierEvents:function(){let a=this;a.n.promagnifier.on("click",function(b){a.n.search.attr("asl-compact");a.keycode=b.keyCode||b.which;a.ktype=b.type;let d;null==(d=a.gaEvent)||d.call(a,"magnifier");if(a.n.text.val().length>=a.o.charcount&&1==a.o.redirectOnClick&&"first_result"!=a.o.trigger.click)return a.doRedirectToResults("click"),clearTimeout(void 0),!1;if("ajax_search"!=a.o.trigger.click&&"first_result"!=a.o.trigger.click)return!1;
a.searchAbort();clearTimeout(a.timeouts.search);a.n.proloading.css("display","none");a.timeouts.search=setTimeout(function(){c("form",a.n.searchsettings).serialize()+a.n.text.val().trim()!=a.lastSuccesfulSearch||!a.resultsOpened&&!a.usingLiveLoader?a.search():a.isRedirectToFirstResult()?a.doRedirectToFirstResult():a.n.proclose.css("display","block")},a.o.trigger.delay)})}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initFacetEvents:function(){let a=this;c("input[type=checkbox]",a.n.searchsettings).on("asl_chbx_change",function(b){a.ktype=b.type;a.n.searchsettings.find("input[name=filters_changed]").val(1);let d;null==(d=a.gaEvent)||d.call(a,"facet_change",{option_label:c(this).closest("fieldset").find("legend").text(),option_value:c(this).closest(".asl_option").find(".asl_option_label").text()+(c(this).prop("checked")?"(checked)":"(unchecked)")});a.setFilterStateInput(65);
a.searchWithCheck(80)})}})})(WPD.dom);
(function(c){let a=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initInputEvents:function(){this._initFocusInput();this.o.trigger.type&&this._initSearchInput();this._initEnterEvent();this._initFormEvent()},_initFocusInput:function(){let b=this;b.n.text.on("click",function(d){d.stopPropagation();d.stopImmediatePropagation();c(this).trigger("focus");let e;null==(e=b.gaEvent)||e.call(b,"focus");if(c("form",b.n.searchsettings).serialize()+b.n.text.val().trim()==b.lastSuccesfulSearch)return b.resultsOpened||
b.usingLiveLoader||(b._no_animations=!0,b.showResults(),b._no_animations=!1),!1});b.n.text.on("focus input",function(d){b.searching||(""!=c(this).val()?b.n.proclose.css("display","block"):b.n.proclose.css({display:"none"}))})},_initSearchInput:function(){let b=this,d=b.n.text.val();b.n.text.on("input",function(e){b.keycode=e.keyCode||e.which;b.ktype=e.type;if(a.detectIE()){if(d==b.n.text.val())return!1;d=b.n.text.val()}if(b.n.text.val().length<b.o.charcount){b.n.proloading.css("display","none");if(0==
b.o.blocking){let f;null==(f=b.hideSettings)||f.call(b)}b.hideResults(!1);b.searchAbort();clearTimeout(b.timeouts.search);return!1}b.searchAbort();clearTimeout(b.timeouts.search);b.n.proloading.css("display","none");b.timeouts.search=setTimeout(function(){c("form",b.n.searchsettings).serialize()+b.n.text.val().trim()!=b.lastSuccesfulSearch||!b.resultsOpened&&!b.usingLiveLoader?b.search():b.isRedirectToFirstResult()?b.doRedirectToFirstResult():b.n.proclose.css("display","block")},b.o.trigger.delay)})},
_initEnterEvent:function(){let b=this,d,e=!1;b.n.text.on("keyup",function(f){b.keycode=f.keyCode||f.which;b.ktype=f.type;if(13==b.keycode){clearTimeout(d);d=setTimeout(function(){e=!1},300);if(e)return!1;e=!0}f=c(this).hasClass("orig");if(b.n.text.val().length>=b.o.charcount&&f&&13==b.keycode){let g;null==(g=b.gaEvent)||g.call(b,"return");1==b.o.redirectOnEnter?"first_result"!=b.o.trigger.return?b.doRedirectToResults(b.ktype):b.search():"ajax_search"==b.o.trigger.return&&(c("form",b.n.searchsettings).serialize()+
b.n.text.val().trim()!=b.lastSuccesfulSearch||!b.resultsOpened&&!b.usingLiveLoader)&&b.search();clearTimeout(b.timeouts.search)}})},_initFormEvent:function(){let b=this;c(b.n.text.closest("form").get(0)).on("submit",function(d,e){d.preventDefault();a.isMobile()?b.o.redirectOnEnter?(d=new Event("keyup"),d.keyCode=d.which=13,this.n.text.get(0).dispatchEvent(d)):(b.search(),document.activeElement.blur()):"undefined"!=typeof e&&"ajax"==e&&b.search()})}})})(WPD.dom);
(function(c){let a=window.WPD.ajaxsearchlite,b=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initOtherEvents:function(){let d=this;if(b.isMobile()&&b.detectIOS())d.n.text.on("touchstart",function(){d.savedScrollTop=window.scrollY;d.savedContainerTop=d.n.search.offset().top});d.n.proclose.on(d.clickTouchend,function(f){f.preventDefault();f.stopImmediatePropagation();d.n.text.val("");d.n.textAutocomplete.val("");d.hideResults();d.n.text.trigger("focus");d.n.proloading.css("display",
"none");d.hideLoader();d.searchAbort();0<c(".asl_es_"+d.o.id).length?(d.showLoader(),d.liveLoad(".asl_es_"+d.o.id,d.getCurrentLiveURL(),!1)):d.o.resPage.useAjax&&(d.showLoader(),d.liveLoad(d.o.resPage.selector,d.getRedirectURL()));d.n.text.get(0).focus()});if(b.isMobile()){var e=function(){d.orientationChange();setTimeout(function(){d.orientationChange()},600)};d.documentEventHandlers.push({node:window,event:"orientationchange",handler:e});c(window).on("orientationchange",e)}else e=function(){d.resize()},
d.documentEventHandlers.push({node:window,event:"resize",handler:e}),c(window).on("resize",e,{passive:!0});e=function(){d.scrolling(!1)};d.documentEventHandlers.push({node:window,event:"scroll",handler:e});c(window).on("scroll",e,{passive:!0});if(b.isMobile()&&""!=d.o.mobile.menu_selector)c(d.o.mobile.menu_selector).on("touchend",function(){let f=this;setTimeout(function(){let g=c(f).find("input.orig");g=0==g.length?c(f).next().find("input.orig"):g;g=0==g.length?c(f).parent().find("input.orig"):g;
g=0==g.length?d.n.text:g;d.n.search.is(":visible")&&g.get(0).focus()},300)});b.detectIOS()&&b.isMobile()&&b.isTouchDevice()&&16>parseInt(d.n.text.css("font-size"))&&(d.n.text.data("fontSize",d.n.text.css("font-size")).css("font-size","16px"),d.n.textAutocomplete.css("font-size","16px"),c("body").append("<style>#ajaxsearchlite"+d.o.rid+" input.orig::-webkit-input-placeholder{font-size: 16px !important;}</style>"))},orientationChange:function(){this.detectAndFixFixedPositioning();this.fixSettingsPosition();
this.fixResultsPosition();"isotopic"==this.o.resultstype&&"visible"==this.n.resultsDiv.css("visibility")&&(this.calculateIsotopeRows(),this.showPagination(!0),this.removeAnimation())},resize:function(){this.detectAndFixFixedPositioning();this.fixSettingsPosition();this.fixResultsPosition();"isotopic"==this.o.resultstype&&"visible"==this.n.resultsDiv.css("visibility")&&(this.calculateIsotopeRows(),this.showPagination(!0),this.removeAnimation())},scrolling:function(d){this.detectAndFixFixedPositioning();
this.hideOnInvisibleBox();this.fixSettingsPosition(d);this.fixResultsPosition(d)},initTryThisEvents:function(){let d=this;d.n.trythis.find("a").on("click touchend",function(e){e.preventDefault();e.stopImmediatePropagation();document.activeElement.blur();d.n.textAutocomplete.val("");d.n.text.val(c(this).html());let f;null==(f=d.gaEvent)||f.call(d,"try_this");setTimeout(function(){d.n.text.trigger("input")},50)})},initPrevState:function(){let d=this;a.firstIteration&&null==a.prevState&&(a.prevState=
localStorage.getItem("asl-"+WPD.Base64.encode(location.href)),null!=a.prevState&&(a.prevState=JSON.parse(a.prevState),a.prevState.settings=WPD.Base64.decode(a.prevState.settings)));if(null!=a.prevState&&"undefined"!=typeof a.prevState.id&&(a.prevState.trigger&&a.prevState.id==d.o.id&&a.prevState.instance==d.o.iid&&(""!=a.prevState.phrase&&(d.triggerPrevState=!0,d.n.text.val(a.prevState.phrase)),b.formData(c("form",d.n.searchsettings))!=a.prevState.settings&&(d.triggerPrevState=!0,d.settingsChanged=
!0,b.formData(c("form",d.n.searchsettings),a.prevState.settings)),null!==a.prevState.settingsOriginal&&(d.originalFormData=WPD.Base64.decode(a.prevState.settingsOriginal),d.setFilterStateInput(0))),"block"==d.o.resultsposition)){let f=!0;d.n.search.on("asl_results_show",function(){f&&(f=!1,setTimeout(function(){let g=0<c(a.prevState.scrollTo).length?c(a.prevState.scrollTo).offset().top:d.n.resultsDiv.find(".item").last().offset().top;window.scrollTo({top:g,behavior:"instant"})},500))})}localStorage.removeItem("asl-"+
WPD.Base64.encode(location.href));let e=function(){var f=d.n.text.val();f={id:d.o.id,trigger:""!=f||d.settingsChanged,instance:d.o.iid,phrase:f,settingsOriginal:"undefined"===typeof d.originalFormData?null:WPD.Base64.encode(d.originalFormData),settings:WPD.Base64.encode(b.formData(c("form",d.n.searchsettings)))};localStorage.setItem("asl-"+WPD.Base64.encode(location.href),JSON.stringify(f))};c(".asl_es_"+d.o.id).on("click","a",e);d.n.resultsDiv.on("click",".results .item",e);d.documentEventHandlers.push({node:document.body,
event:"asl_memorize_state_"+d.o.id,handler:e});c("body").on("asl_memorize_state_"+d.o.id,e)}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initResultsEvents:function(){let a=this;a.n.resultsDiv.css({opacity:"0"});let b=function(d){let e=d.keyCode||d.which,f=d.type;if(0==c(d.target).closest(".asl_w").length){if(0==a.o.blocking&&!a.dragging){let g;null==(g=a.hideSettings)||g.call(a)}a.hideOnInvisibleBox();"click"==f&&"touchend"==f&&3==e||0==a.resultsOpened||1!=a.o.closeOnDocClick||a.dragging||(a.hideLoader(),a.searchAbort(),a.hideResults())}};a.documentEventHandlers.push({node:document,
event:a.clickTouchend,handler:b});c(document).on(a.clickTouchend,b)}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initSettingsEvents:function(){let a=this;a.n.searchsettings.on("click",function(){a.settingsChanged=!0});a.n.searchsettings.on(a.clickTouchend,function(b){"undefined"==typeof b.target||c(b.target).hasClass("noUi-handle")||b.stopImmediatePropagation()});a.n.prosettings.on("click",function(){0==a.n.prosettings.data("opened")?a.showSettings():a.hideSettings()});1==a.o.settingsVisible&&a.showSettings(!1);c('.asl_option_cat input[type="checkbox"]',
a.n.searchsettings).on("asl_chbx_change",function(){a.settingsCheckboxToggle(c(this).closest(".asl_option_cat"))});c(".asl_option_cat",a.n.searchsettings).forEach(function(b){a.settingsCheckboxToggle(c(b),!1)})}})})(WPD.dom);(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{monitorTouchMove:function(){let a=this;a.dragging=!1;c("body").on("touchmove",function(){a.dragging=!0}).on("touchstart",function(){a.dragging=!1})}})})(WPD.dom);
(function(c){let a=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initEtc:function(){let b=this,d=null;b.n.trythis.css({visibility:"visible"});c("div.asl_option",b.n.searchsettings).on(b.mouseupTouchend,function(e){e.preventDefault();e.stopImmediatePropagation();if(b.dragging)return!1;c(this).find('input[type="checkbox"]').prop("checked",!c(this).find('input[type="checkbox"]').prop("checked"));clearTimeout(d);let f=this;d=setTimeout(function(){c(f).find('input[type="checkbox"]').trigger("asl_chbx_change")},
50)});c("div.asl_option label",b.n.searchsettings).on("click",function(e){e.preventDefault()});c("fieldset.asl_checkboxes_filter_box",b.n.searchsettings).forEach(function(){let e=!0;c(this).find('.asl_option:not(.asl_option_selectall) input[type="checkbox"]').forEach(function(){if(1==c(this).prop("checked"))return e=!1});e&&c(this).find('.asl_option_selectall input[type="checkbox"]').prop("checked",!1).removeAttr("data-origvalue")});c("fieldset",b.n.searchsettings).forEach(function(){c(this).find(".asl_option:not(.hiddend)").last().addClass("asl-o-last")});
c('.asl_option_cat input[type="checkbox"], .asl_option_cff input[type="checkbox"]',b.n.searchsettings).on("asl_chbx_change",function(){let e=c(this).data("targetclass");"string"==typeof e&&""!=e&&c("input."+e,b.n.searchsettings).prop("checked",c(this).prop("checked"))});b.n.resultsDiv.on("click",".results .item",function(){let e;null==(e=b.gaEvent)||e.call(b,"result_click",{result_title:c(this).find("a.asl_res_url").text(),result_url:c(this).find("a.asl_res_url").attr("href")});1==b.o.singleHighlight&&
(localStorage.removeItem("asl_phrase_highlight"),""!=b.n.text.val().replace(/["']/g,"")&&localStorage.setItem("asl_phrase_highlight",JSON.stringify({phrase:b.n.text.val().replace(/["']/g,"")})))});a.Hooks.addFilter("asl/init/etc",b)}})})(WPD.dom);
(function(c){let a=window.WPD.ajaxsearchlite,b=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{init:function(d,e){this.autopStartedTheSearch=this.isAutoP=this.triggerPrevState=this.searching=!1;this.autopData={};this.resultsOpened=this.settingsChanged=!1;this.postAuto=this.post=null;this.scroll={};this.savedContainerTop=this.savedScrollTop=0;this.is_scroll="undefined"!=typeof asp_SimpleBar;this.disableMobileScroll=!1;this.clickTouchend="click touchend";this.mouseupTouchend=
"mouseup touchend";this.noUiSliders=[];this.timeouts={compactBeforeOpen:null,compactAfterOpen:null,search:null,searchWithCheck:null};this.eh={};this.documentEventHandlers=[];this.settScroll=null;this.currentPage=1;this.sIsotope=this.isotopic=null;this.lastSuccesfulSearch="";this.lastSearchData={};this._no_animations=!1;this.results_num=this.call_num=0;this.o=c.fn.extend({},d);this.n={};this.n.search=c(e);this.initNodeVariables();b.isMobile()?this.animOptions=this.o.animations.mob:this.animOptions=
this.o.animations.pc;this.animationOpacity=0>this.animOptions.items.indexOf("In")?"opacityOne":"opacityZero";this.o.redirectOnClick="ajax_search"!=this.o.trigger.click&&"nothing"!=this.o.trigger.click;this.o.redirectOnEnter="ajax_search"!=this.o.trigger.return&&"nothing"!=this.o.trigger.return;if(this.usingLiveLoader=this.o.resPage.useAjax&&0<c(this.o.resPage.selector).length||0<c(".asl_es_"+this.o.id).length)this.o.trigger.type=this.o.resPage.trigger_type,this.o.trigger.facet=this.o.resPage.trigger_facet,
this.o.resPage.trigger_magnifier&&(this.o.redirectOnClick=0,this.o.trigger.click="ajax_search"),this.o.resPage.trigger_return&&(this.o.redirectOnEnter=0,this.o.trigger.return="ajax_search");this.o.trigger.redirect_url=b.decodeHTMLEntities(this.o.trigger.redirect_url);this.n.textAutocomplete.val("");1==ASL.js_retain_popstate&&this.initPrevState();this.detectAndFixFixedPositioning();this.monitorTouchMove();"undefined"!==typeof this.initSettingsAnimations&&this.initSettingsAnimations();this.initResultsAnimations();
this.initEvents();this.initEtc();a.firstIteration=!1;"undefined"===typeof this.originalFormData&&(this.originalFormData=b.formData(c("form",this.n.searchsettings)));this.n.s.trigger("asl_init_search_bar",[this.o.id,this.o.iid],!0,!0);return this},initNodeVariables:function(){this.n.s=this.n.search;this.n.container=this.n.search.closest(".asl_w_container");this.o.id=this.n.search.data("id");this.o.iid=this.n.search.data("instance");this.o.rid=this.o.id;this.o.name=this.n.search.data("name");this.n.searchsettings=
c(".asl_s",this.n.container);this.n.resultsDiv=c(".asl_r",this.n.container);this.n.probox=c(".probox",this.n.search);this.n.proinput=c(".proinput",this.n.search);this.n.text=c(".proinput input.orig",this.n.search);this.n.textAutocomplete=c(".proinput input.autocomplete",this.n.search);this.n.loading=c(".proinput .loading",this.n.search);this.n.proloading=c(".proloading",this.n.search);this.n.proclose=c(".proclose",this.n.search);this.n.promagnifier=c(".promagnifier",this.n.search);this.n.prosettings=
c(".prosettings",this.n.search);this.fixClonedSelf();this.n.settingsAppend=c("#wpdreams_asl_settings_"+this.o.id);this.o.blocking=this.n.searchsettings.hasClass("asl_sb");"undefined"!==typeof this.initSettingsBox&&this.initSettingsBox();this.n.trythis=c("#asl-try-"+this.o.rid);this.n.resultsAppend=c("#wpdreams_asl_results_"+this.o.id);this.initResultsBox();this.n.hiddenContainer=c(".asl_hidden_data",this.n.container);this.n.aslItemOverlay=c(".asp_item_overlay",this.n.hiddenContainer);this.n.showmore=
c(".showmore",this.n.resultsDiv);this.n.items=0<c(".item",this.n.resultsDiv).length?c(".item",this.n.resultsDiv):c(".photostack-flip",this.n.resultsDiv);this.n.results=c(".results",this.n.resultsDiv);this.n.resdrg=c(".resdrg",this.n.resultsDiv)},initEvents:function(){"undefined"!==typeof this.initSettingsEvents&&this.initSettingsEvents();this.initResultsEvents();this.initOtherEvents();this.initTryThisEvents();this.initMagnifierEvents();this.initInputEvents();let d;null==(d=this.initAutocompleteEvent)||
d.call(this);let e;null==(e=this.initFacetEvents)||e.call(this)}})})(WPD.dom);
(function(c){let a=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initResultsBox:function(){a.isMobile()&&1==this.o.mobile.force_res_hover?(this.o.resultsposition="hover",this.n.resultsDiv=this.n.resultsDiv.clone(),c("body").append(this.n.resultsDiv),this.n.resultsDiv.css({position:"absolute"}),this.detectAndFixFixedPositioning()):"hover"==this.o.resultsposition&&0>=this.n.resultsAppend.length?(this.n.resultsDiv=this.n.resultsDiv.clone(),c("body").append(this.n.resultsDiv)):
(this.o.resultsposition="block",this.n.resultsDiv.css({position:"static"}),0<this.n.resultsAppend.length&&(0<this.n.resultsAppend.find(".asl_w").length?(this.n.resultsDiv=this.n.resultsAppend.find(".asl_w"),this.n.showmore=c(".showmore",this.n.resultsDiv),this.n.items=0<c(".item",this.n.resultsDiv).length?c(".item",this.n.resultsDiv):c(".photostack-flip",this.n.resultsDiv),this.n.results=c(".results",this.n.resultsDiv),this.n.resdrg=c(".resdrg",this.n.resultsDiv)):(this.n.resultsDiv=this.n.resultsDiv.clone(),
this.n.resultsAppend.append(this.n.resultsDiv))));this.n.resultsDiv.get(0).id=this.n.resultsDiv.get(0).id.replace("__original__","")},initResultsAnimations:function(){this.resAnim={showClass:"asl_an_fadeInDrop",showCSS:{visibility:"visible",display:"block",opacity:1,"animation-duration":"300ms"},hideClass:"asl_an_fadeOutDrop",hideCSS:{visibility:"hidden",opacity:0,display:"none"},duration:300};this.n.resultsDiv.css({"-webkit-animation-duration":"300ms","animation-duration":"300ms"})}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initSettingsBox:function(){let a=this;(function(b){let d=a.n.searchsettings.get(0);a.n.searchsettings=a.n.searchsettings.clone();b.append(a.n.searchsettings);c(d).find("*[id]").forEach(function(e){0>e.id.indexOf("__original__")&&(e.id="__original__"+e.id)});a.n.searchsettings.find("*[id]").forEach(function(e){-1<e.id.indexOf("__original__")&&(e.id=e.id.replace("__original__",""))})})(c("body"));a.n.searchsettings.get(0).id=a.n.searchsettings.get(0).id.replace("__original__",
"")},initSettingsAnimations:function(){this.settAnim={showClass:"",showCSS:{visibility:"visible",display:"block",opacity:1,"animation-duration":this.animOptions.settings.dur+"ms"},hideClass:"",hideCSS:{visibility:"hidden",opacity:0,display:"none"},duration:this.animOptions.settings.dur+"ms"};"fade"==this.animOptions.settings.anim&&(this.settAnim.showClass="asl_an_fadeIn",this.settAnim.hideClass="asl_an_fadeOut");"fadedrop"!=this.animOptions.settings.anim||this.o.blocking?"fadedrop"==this.animOptions.settings.anim&&
(this.settAnim.showClass="asl_an_fadeIn",this.settAnim.hideClass="asl_an_fadeOut"):(this.settAnim.showClass="asl_an_fadeInDrop",this.settAnim.hideClass="asl_an_fadeOutDrop");this.n.searchsettings.css({"-webkit-animation-duration":this.settAnim.duration+"ms","animation-duration":this.settAnim.duration+"ms"})}})})(WPD.dom);window.ASL="undefined"!==typeof window.ASL?window.ASL:{};
window.ASL.api=function(){let c=function(d,e,f,g){d=ASL.instances.get(d,e);return!1!==d&&d[f].apply(d,[g])},a=function(d,e,f){if(!isNaN(parseFloat(e))&&isFinite(e))return d=ASL.instances.get(d,e),!1!==d&&d[f].apply(d);d=ASL.instances.get(d);return!1!==d&&d.forEach(function(g){g[e].apply(g,[f])})},b=function(d,e){if("exists"==e)return ASL.instances.exist(d);d=ASL.instances.get(d);return!1!==d&&d.forEach(function(f){f[e].apply(f)})};if(4==arguments.length)return c.apply(this,arguments);if(3==arguments.length)return a.apply(this,
arguments);if(2==arguments.length)return b.apply(this,arguments);0==arguments.length&&(console.log("Usage: ASL.api(id, [optional]instance, function, [optional]args);"),console.log("For more info: https://knowledgebase.ajaxsearchlite.com/other/javascript-api"))};
window._ASL_load=function(){let c=WPD.dom;window.ASL.instances={instances:[],get:function(a,b){this.clean();if("undefined"===typeof a||0==a)return this.instances;if("undefined"===typeof b){b=[];for(var d=0;d<this.instances.length;d++)this.instances[d].o.id==a&&b.push(this.instances[d]);return 0<b.length?b:!1}for(d=0;d<this.instances.length;d++)if(this.instances[d].o.id==a&&this.instances[d].o.iid==b)return this.instances[d];return!1},set:function(a){if(this.exist(a.o.id,a.o.iid))return!1;this.instances.push(a);
return!0},exist:function(a,b){this.clean();for(let d=0;d<this.instances.length;d++)if(this.instances[d].o.id==a&&("undefined"===typeof b||this.instances[d].o.iid==b))return!0;return!1},clean:function(){let a=[],b=this;this.instances.forEach(function(d,e){0==c(".asl_m_"+d.o.rid).length&&a.push(e)});a.forEach(function(d){"undefined"!==typeof b.instances[d]&&(b.instances[d].destroy(),b.instances.splice(d,1))})},destroy:function(a,b){let d=this.get(a,b);if(!1!==d)if(Array.isArray(d))d.forEach(function(e){e.destroy()}),
this.instances=[];else{let e=0;this.instances.forEach(function(f,g){f.o.id==a&&f.o.iid==b&&(e=g)});d.destroy();this.instances.splice(e,1)}}};window.ASL.initialized=!1;window.ASL.initializeById=function(a,b){let d=".asl_init_data";b="undefined"==typeof b?!1:b;"undefined"!==typeof a&&"object"!=typeof a&&(d="div[id*=asl_init_id_"+a+"]");let e=0;c(d).forEach(function(f){let g=c(f).closest(".asl_w_container").find(".asl_m");if(0==g.length||"undefined"!=typeof g.get(0).hasAsl)return++e,!0;if(!b&&!g.inViewPort(-100))return!0;
f=c(f).data("asldata");if("undefined"===typeof f)return!0;f=WPD.Base64.decode(f);if("undefined"===typeof f||""==f)return!0;f=JSON.parse(f);g.get(0).hasAsl=!0;++e;return g.ajaxsearchlite(f)});c(d).length==e&&(document.removeEventListener("scroll",ASL.initializeById),document.removeEventListener("resize",ASL.initializeById))};window.ASL.initialize=function(a){if("undefined"==typeof this.version)return!1;ASL.script_async_load?(document.addEventListener("scroll",ASL.initializeById,{passive:!0}),document.addEventListener("resize",
ASL.initializeById,{passive:!0}),ASL.initializeById(a)):ASL.initializeById(a,!0);if(this.highlight.enabled){let b=localStorage.getItem("asl_phrase_highlight");localStorage.removeItem("asl_phrase_highlight");null!=b&&(b=JSON.parse(b),this.highlight.data.forEach(function(d){var e=""!=d.selector&&0<c(d.selector).length?d.selector:"article";e=0<c(e).length?e:"body";c(e).highlight(b.phrase,{element:"span",className:"asl_single_highlighted",wordsOnly:d.whole,excludeParents:".asl_w, .asl-try"});e=c(".asl_single_highlighted");
if(d.scroll&&0<e.length){e=e.offset().top-120;let f=c("#wpadminbar");0<f.length&&(e-=f.height());e+=d.scroll_offset;e=0>e?0:e;c("html").animate({scrollTop:e},500)}return!1}))}this.initialized=!0};window.ASL.ready=function(){let a=this,b=c("body"),d,e,f;ASL.script_async_load&&a.initialize();c(document).on("DOMContentLoaded",function(){a.initialize()});if("undefined"!=typeof ASL.detect_ajax&&1==ASL.detect_ajax){let g=new MutationObserver(function(){clearTimeout(d);d=setTimeout(function(){a.initialize()},
500)});function h(){let k=document.querySelector("body");k?g.observe(k,{subtree:!0,childList:!0}):window.setTimeout(h,500)}h()}c(window).on("resize",function(){clearTimeout(e);e=setTimeout(function(){a.initializeById()},200)});b.on("click touchend","#menu-item-search, .fa-search, .fa, .fas, .fusion-flyout-menu-toggle, .fusion-main-menu-search-open, #search_button, .mini-search.popup-search, .icon-search, .menu-item-search-dropdown, .mobile-menu-button, .td-icon-search, .tdb-search-icon, .side_menu_button, .search_button, .raven-search-form-toggle, [data-elementor-open-lightbox], .elementor-button-link, .elementor-button, i[class*=-search], a[class*=-search]",
function(){clearTimeout(f);f=setTimeout(function(){a.initializeById({},!0)},300)});if("undefined"!=typeof jQuery)jQuery(document).on("elementor/popup/show",function(){setTimeout(function(){a.initializeById({},!0)},10)})};window.ASL.loadScriptStack=function(a){let b;0<a.length&&(b=document.createElement("script"),b.src=a.shift().src,b.onload=function(){0<a.length?window.ASL.loadScriptStack(a):window.ASL.ready()},document.body.appendChild(b))};window.ASL.init=function(){ASL.script_async_load?window.ASL.loadScriptStack(ASL.additional_scripts):
"undefined"!==typeof WPD.ajaxsearchlite&&window.ASL.ready()};window.ASL.css_async&&"undefined"==typeof window.ASL.css_loaded||window.WPD.intervalUntilExecute(window.ASL.init,function(){return"undefined"!=typeof window.ASL.version&&"undefined"!=c.fn.ajaxsearchlite})};(function(){"undefined"!=typeof WPD&&"undefined"!=typeof WPD.dom?window._ASL_load():document.addEventListener("wpd-dom-core-loaded",window._ASL_load)})();
